### ISSUE TITLE
await

### ISSUE THREAD

**Issue by cjessett** [jherediagu/CodeAcademy-TDD-VidBits#2]
(Simplify) [Using a callback with `await`](https://github.com/jherediagu/CodeAcademy-TDD-VidBits/blob/e0e6d34b764462dc204bfe9049df7f1956c98850/routes/videos.js#L31-L33) is an anti-pattern. The point of `await` is to make our async code look synchronous, using a callback with `await` defeats the purpose. Instead, just omit the callback since there is a general error handling function in `app.js`.

**Comment by jherediagu** [comment]
Thank you so much for your comments, I've already fixed it :)
